//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rohab.ServiceReference1
{
    using System.Runtime.Serialization;
    using System;


    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    //[System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    //[System.SerializableAttribute()]
    ////public class ArrayOfString : System.Collections.Generic.List<string> {
    ////}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    //[System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    //[System.SerializableAttribute()]
    ////public class ArrayOfLong : System.Collections.Generic.List<long> {
    ////}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    //[System.SerializableAttribute()]
    ////public partial class MessagesBL : Rohab.ServiceReference1.BaseBL {

    ////    private long MsgIDField;

    ////    private int UserIDField;

    ////    private int LinkIDField;

    ////    private int NumberIDField;

    ////    private double TariffField;

    ////    private byte MsgTypeField;

    ////    [System.Runtime.Serialization.OptionalFieldAttribute()]
    ////    private string BodyField;

    ////    [System.Runtime.Serialization.OptionalFieldAttribute()]
    ////    private string UdhField;

    ////    private System.DateTime SendDateField;

    ////    [System.Runtime.Serialization.OptionalFieldAttribute()]
    ////    private string SenderField;

    ////    [System.Runtime.Serialization.OptionalFieldAttribute()]
    ////    private string ReceiverField;

    ////    private int FirstLocationField;

    ////    private int CurrentLocationField;

    ////    private int PartsField;

    ////    private bool IsFlashField;

    ////    private bool IsReadField;

    ////    private bool IsUnicodeField;

    ////    private double CreditField;

    ////    private int ModuleField;

    ////    private int RecCountField;

    ////    private int RecFailedField;

    ////    private int RecSuccessField;

    ////    private bool IsMoneyBackField;

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    ////    public long MsgID {
    ////        get {
    ////            return this.MsgIDField;
    ////        }
    ////        set {
    ////            if ((this.MsgIDField.Equals(value) != true)) {
    ////                this.MsgIDField = value;
    ////                this.RaisePropertyChanged("MsgID");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    ////    public int UserID {
    ////        get {
    ////            return this.UserIDField;
    ////        }
    ////        set {
    ////            if ((this.UserIDField.Equals(value) != true)) {
    ////                this.UserIDField = value;
    ////                this.RaisePropertyChanged("UserID");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
    ////    public int LinkID {
    ////        get {
    ////            return this.LinkIDField;
    ////        }
    ////        set {
    ////            if ((this.LinkIDField.Equals(value) != true)) {
    ////                this.LinkIDField = value;
    ////                this.RaisePropertyChanged("LinkID");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
    ////    public int NumberID {
    ////        get {
    ////            return this.NumberIDField;
    ////        }
    ////        set {
    ////            if ((this.NumberIDField.Equals(value) != true)) {
    ////                this.NumberIDField = value;
    ////                this.RaisePropertyChanged("NumberID");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
    ////    public double Tariff {
    ////        get {
    ////            return this.TariffField;
    ////        }
    ////        set {
    ////            if ((this.TariffField.Equals(value) != true)) {
    ////                this.TariffField = value;
    ////                this.RaisePropertyChanged("Tariff");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
    ////    public byte MsgType {
    ////        get {
    ////            return this.MsgTypeField;
    ////        }
    ////        set {
    ////            if ((this.MsgTypeField.Equals(value) != true)) {
    ////                this.MsgTypeField = value;
    ////                this.RaisePropertyChanged("MsgType");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    ////    public string Body {
    ////        get {
    ////            return this.BodyField;
    ////        }
    ////        set {
    ////            if ((object.ReferenceEquals(this.BodyField, value) != true)) {
    ////                this.BodyField = value;
    ////                this.RaisePropertyChanged("Body");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    ////    public string Udh {
    ////        get {
    ////            return this.UdhField;
    ////        }
    ////        set {
    ////            if ((object.ReferenceEquals(this.UdhField, value) != true)) {
    ////                this.UdhField = value;
    ////                this.RaisePropertyChanged("Udh");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
    ////    public System.DateTime SendDate {
    ////        get {
    ////            return this.SendDateField;
    ////        }
    ////        set {
    ////            if ((this.SendDateField.Equals(value) != true)) {
    ////                this.SendDateField = value;
    ////                this.RaisePropertyChanged("SendDate");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
    ////    public string Sender {
    ////        get {
    ////            return this.SenderField;
    ////        }
    ////        set {
    ////            if ((object.ReferenceEquals(this.SenderField, value) != true)) {
    ////                this.SenderField = value;
    ////                this.RaisePropertyChanged("Sender");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
    ////    public string Receiver {
    ////        get {
    ////            return this.ReceiverField;
    ////        }
    ////        set {
    ////            if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
    ////                this.ReceiverField = value;
    ////                this.RaisePropertyChanged("Receiver");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
    ////    public int FirstLocation {
    ////        get {
    ////            return this.FirstLocationField;
    ////        }
    ////        set {
    ////            if ((this.FirstLocationField.Equals(value) != true)) {
    ////                this.FirstLocationField = value;
    ////                this.RaisePropertyChanged("FirstLocation");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
    ////    public int CurrentLocation {
    ////        get {
    ////            return this.CurrentLocationField;
    ////        }
    ////        set {
    ////            if ((this.CurrentLocationField.Equals(value) != true)) {
    ////                this.CurrentLocationField = value;
    ////                this.RaisePropertyChanged("CurrentLocation");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
    ////    public int Parts {
    ////        get {
    ////            return this.PartsField;
    ////        }
    ////        set {
    ////            if ((this.PartsField.Equals(value) != true)) {
    ////                this.PartsField = value;
    ////                this.RaisePropertyChanged("Parts");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
    ////    public bool IsFlash {
    ////        get {
    ////            return this.IsFlashField;
    ////        }
    ////        set {
    ////            if ((this.IsFlashField.Equals(value) != true)) {
    ////                this.IsFlashField = value;
    ////                this.RaisePropertyChanged("IsFlash");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
    ////    public bool IsRead {
    ////        get {
    ////            return this.IsReadField;
    ////        }
    ////        set {
    ////            if ((this.IsReadField.Equals(value) != true)) {
    ////                this.IsReadField = value;
    ////                this.RaisePropertyChanged("IsRead");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
    ////    public bool IsUnicode {
    ////        get {
    ////            return this.IsUnicodeField;
    ////        }
    ////        set {
    ////            if ((this.IsUnicodeField.Equals(value) != true)) {
    ////                this.IsUnicodeField = value;
    ////                this.RaisePropertyChanged("IsUnicode");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
    ////    public double Credit {
    ////        get {
    ////            return this.CreditField;
    ////        }
    ////        set {
    ////            if ((this.CreditField.Equals(value) != true)) {
    ////                this.CreditField = value;
    ////                this.RaisePropertyChanged("Credit");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
    ////    public int Module {
    ////        get {
    ////            return this.ModuleField;
    ////        }
    ////        set {
    ////            if ((this.ModuleField.Equals(value) != true)) {
    ////                this.ModuleField = value;
    ////                this.RaisePropertyChanged("Module");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
    ////    public int RecCount {
    ////        get {
    ////            return this.RecCountField;
    ////        }
    ////        set {
    ////            if ((this.RecCountField.Equals(value) != true)) {
    ////                this.RecCountField = value;
    ////                this.RaisePropertyChanged("RecCount");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
    ////    public int RecFailed {
    ////        get {
    ////            return this.RecFailedField;
    ////        }
    ////        set {
    ////            if ((this.RecFailedField.Equals(value) != true)) {
    ////                this.RecFailedField = value;
    ////                this.RaisePropertyChanged("RecFailed");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
    ////    public int RecSuccess {
    ////        get {
    ////            return this.RecSuccessField;
    ////        }
    ////        set {
    ////            if ((this.RecSuccessField.Equals(value) != true)) {
    ////                this.RecSuccessField = value;
    ////                this.RaisePropertyChanged("RecSuccess");
    ////            }
    ////        }
    ////    }

    ////    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
    ////    public bool IsMoneyBack {
    ////        get {
    ////            return this.IsMoneyBackField;
    ////        }
    ////        set {
    ////            if ((this.IsMoneyBackField.Equals(value) != true)) {
    ////                this.IsMoneyBackField = value;
    ////                this.RaisePropertyChanged("IsMoneyBack");
    ////            }
    ////        }
    ////    }
    ////}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    //[System.SerializableAttribute()]
    //[System.Runtime.Serialization.KnownTypeAttribute(typeof(Rohab.ServiceReference1.MessagesBL))]
    //public partial class BaseBL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

    //    //[System.NonSerializedAttribute()]
    //    //private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    //    //[global::System.ComponentModel.BrowsableAttribute(false)]
    //    //public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
    //    //    get {
    //    //        return this.extensionDataField;
    //    //    }
    //    //    set {
    //    //        this.extensionDataField = value;
    //    //    }
    //    //}

    //    //public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    //    //protected void RaisePropertyChanged(string propertyName) {
    //    //    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
    //    //    if ((propertyChanged != null)) {
    //    //        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
    //    //    }
    //    //}
    //}

    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SendSoap")]
    ////public interface SendSoap {

    ////    // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
    ////    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
    ////    Rohab.ServiceReference1.SendSmsResponse SendSms(Rohab.ServiceReference1.SendSmsRequest request);

    ////    // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
    ////    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
    ////    Rohab.ServiceReference1.GetCreditResponse GetCredit(Rohab.ServiceReference1.GetCreditRequest request);

    ////    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
    ////    int GetDelivery(long recId);

    ////    // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
    ////    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
    ////    Rohab.ServiceReference1.GetInboxCountResponse GetInboxCount(Rohab.ServiceReference1.GetInboxCountRequest request);

    ////    // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
    ////    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
    ////    Rohab.ServiceReference1.getMessagesResponse getMessages(Rohab.ServiceReference1.getMessagesRequest request);
    ////}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class SendSmsRequest {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.SendSmsRequestBody Body;

    //    //public SendSmsRequest() {
    //    //}

    //    //public SendSmsRequest(Rohab.ServiceReference1.SendSmsRequestBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class SendSmsRequestBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    //    //public string username;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    //    //public string password;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    //    //public Rohab.ServiceReference1.ArrayOfString to;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    //    //public string from;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    //    //public string text;

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    //    //public bool isflash;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    //    //public string udh;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    //    //public Rohab.ServiceReference1.ArrayOfLong recId;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
    //    //public byte[] status;

    //    //public SendSmsRequestBody() {
    //    //}

    //    //public SendSmsRequestBody(string username, string password, Rohab.ServiceReference1.ArrayOfString to, string from, string text, bool isflash, string udh, Rohab.ServiceReference1.ArrayOfLong recId, byte[] status) {
    //    //    this.username = username;
    //    //    this.password = password;
    //    //    this.to = to;
    //    //    this.from = from;
    //    //    this.text = text;
    //    //    this.isflash = isflash;
    //    //    this.udh = udh;
    //    //    this.recId = recId;
    //    //    this.status = status;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class SendSmsResponse {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.SendSmsResponseBody Body;

    //    //public SendSmsResponse() {
    //    //}

    //    //public SendSmsResponse(Rohab.ServiceReference1.SendSmsResponseBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class SendSmsResponseBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    //    //public int SendSmsResult;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    //    //public Rohab.ServiceReference1.ArrayOfLong recId;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    //    //public byte[] status;

    //    //public SendSmsResponseBody() {
    //    //}

    //    //public SendSmsResponseBody(int SendSmsResult, Rohab.ServiceReference1.ArrayOfLong recId, byte[] status) {
    //    //    this.SendSmsResult = SendSmsResult;
    //    //    this.recId = recId;
    //    //    this.status = status;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class GetCreditRequest {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.GetCreditRequestBody Body;

    //    //public GetCreditRequest() {
    //    //}

    //    //public GetCreditRequest(Rohab.ServiceReference1.GetCreditRequestBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class GetCreditRequestBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    //    //public string username;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    //    //public string password;

    //    //public GetCreditRequestBody() {
    //    //}

    //    //public GetCreditRequestBody(string username, string password) {
    //    //    this.username = username;
    //    //    this.password = password;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class GetCreditResponse {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.GetCreditResponseBody Body;

    //    //public GetCreditResponse() {
    //    //}

    //    //public GetCreditResponse(Rohab.ServiceReference1.GetCreditResponseBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class GetCreditResponseBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    //    //public double GetCreditResult;

    //    //public GetCreditResponseBody() {
    //    //}

    //    //public GetCreditResponseBody(double GetCreditResult) {
    //    //    this.GetCreditResult = GetCreditResult;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class GetInboxCountRequest {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.GetInboxCountRequestBody Body;

    //    //public GetInboxCountRequest() {
    //    //}

    //    //public GetInboxCountRequest(Rohab.ServiceReference1.GetInboxCountRequestBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class GetInboxCountRequestBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    //    //public string username;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    //    //public string password;

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    //    //public bool isRead;

    //    //public GetInboxCountRequestBody() {
    //    //}

    //    //public GetInboxCountRequestBody(string username, string password, bool isRead) {
    //    //    this.username = username;
    //    //    this.password = password;
    //    //    this.isRead = isRead;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class GetInboxCountResponse {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.GetInboxCountResponseBody Body;

    //    //public GetInboxCountResponse() {
    //    //}

    //    //public GetInboxCountResponse(Rohab.ServiceReference1.GetInboxCountResponseBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class GetInboxCountResponseBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    //    //public int GetInboxCountResult;

    //    //public GetInboxCountResponseBody() {
    //    //}

    //    //public GetInboxCountResponseBody(int GetInboxCountResult) {
    //    //    this.GetInboxCountResult = GetInboxCountResult;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class getMessagesRequest {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="getMessages", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.getMessagesRequestBody Body;

    //    //public getMessagesRequest() {
    //    //}

    //    //public getMessagesRequest(Rohab.ServiceReference1.getMessagesRequestBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class getMessagesRequestBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    //    //public string username;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    //    //public string password;

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    //    //public int location;

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    //    //public string from;

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    //    //public int index;

    //    //[System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    //    //public int count;

    //    //public getMessagesRequestBody() {
    //    //}

    //    //public getMessagesRequestBody(string username, string password, int location, string from, int index, int count) {
    //    //    this.username = username;
    //    //    this.password = password;
    //    //    this.location = location;
    //    //    this.from = from;
    //    //    this.index = index;
    //    //    this.count = count;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    //public partial class getMessagesResponse {

    //    //[System.ServiceModel.MessageBodyMemberAttribute(Name="getMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
    //    //public Rohab.ServiceReference1.getMessagesResponseBody Body;

    //    //public getMessagesResponse() {
    //    //}

    //    //public getMessagesResponse(Rohab.ServiceReference1.getMessagesResponseBody Body) {
    //    //    this.Body = Body;
    //    //}
    //}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    //public partial class getMessagesResponseBody {

    //    //[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    //    //public Rohab.ServiceReference1.MessagesBL[] getMessagesResult;

    //    //public getMessagesResponseBody() {
    //    //}

    //    //public getMessagesResponseBody(Rohab.ServiceReference1.MessagesBL[] getMessagesResult) {
    //    //    this.getMessagesResult = getMessagesResult;
    //    //}
    //}

    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    ////public interface SendSoapChannel : Rohab.ServiceReference1.SendSoap, System.ServiceModel.IClientChannel {
    ////}

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    //public partial class SendSoapClient : System.ServiceModel.ClientBase<Rohab.ServiceReference1.SendSoap>, Rohab.ServiceReference1.SendSoap {

    //    //public SendSoapClient() {
    //    //}

    //    //public SendSoapClient(string endpointConfigurationName) : 
    //    //        base(endpointConfigurationName) {
    //    //}

    //    //public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
    //    //        base(endpointConfigurationName, remoteAddress) {
    //    //}

    //    //public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
    //    //        base(endpointConfigurationName, remoteAddress) {
    //    //}

    //    //public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
    //    //        base(binding, remoteAddress) {
    //    //}

    //    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //    //Rohab.ServiceReference1.SendSmsResponse Rohab.ServiceReference1.SendSoap.SendSms(Rohab.ServiceReference1.SendSmsRequest request) {
    //    //    return base.Channel.SendSms(request);
    //    //}

    //    //public int SendSms(string username, string password, Rohab.ServiceReference1.ArrayOfString to, string from, string text, bool isflash, string udh, ref Rohab.ServiceReference1.ArrayOfLong recId, ref byte[] status) {
    //    //    Rohab.ServiceReference1.SendSmsRequest inValue = new Rohab.ServiceReference1.SendSmsRequest();
    //    //    inValue.Body = new Rohab.ServiceReference1.SendSmsRequestBody();
    //    //    inValue.Body.username = username;
    //    //    inValue.Body.password = password;
    //    //    inValue.Body.to = to;
    //    //    inValue.Body.from = from;
    //    //    inValue.Body.text = text;
    //    //    inValue.Body.isflash = isflash;
    //    //    inValue.Body.udh = udh;
    //    //    inValue.Body.recId = recId;
    //    //    inValue.Body.status = status;
    //    //    Rohab.ServiceReference1.SendSmsResponse retVal = ((Rohab.ServiceReference1.SendSoap)(this)).SendSms(inValue);
    //    //    recId = retVal.Body.recId;
    //    //    status = retVal.Body.status;
    //    //    return retVal.Body.SendSmsResult;
    //    //}

    //    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //    //Rohab.ServiceReference1.GetCreditResponse Rohab.ServiceReference1.SendSoap.GetCredit(Rohab.ServiceReference1.GetCreditRequest request) {
    //    //    return base.Channel.GetCredit(request);
    //    //}

    //    //public double GetCredit(string username, string password) {
    //    //    Rohab.ServiceReference1.GetCreditRequest inValue = new Rohab.ServiceReference1.GetCreditRequest();
    //    //    inValue.Body = new Rohab.ServiceReference1.GetCreditRequestBody();
    //    //    inValue.Body.username = username;
    //    //    inValue.Body.password = password;
    //    //    Rohab.ServiceReference1.GetCreditResponse retVal = ((Rohab.ServiceReference1.SendSoap)(this)).GetCredit(inValue);
    //    //    return retVal.Body.GetCreditResult;
    //    //}

    //    //public int GetDelivery(long recId) {
    //    //    return base.Channel.GetDelivery(recId);
    //    //}

    //    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //    //Rohab.ServiceReference1.GetInboxCountResponse Rohab.ServiceReference1.SendSoap.GetInboxCount(Rohab.ServiceReference1.GetInboxCountRequest request) {
    //    //    return base.Channel.GetInboxCount(request);
    //    //}

    //    //public int GetInboxCount(string username, string password, bool isRead) {
    //    //    Rohab.ServiceReference1.GetInboxCountRequest inValue = new Rohab.ServiceReference1.GetInboxCountRequest();
    //    //    inValue.Body = new Rohab.ServiceReference1.GetInboxCountRequestBody();
    //    //    inValue.Body.username = username;
    //    //    inValue.Body.password = password;
    //    //    inValue.Body.isRead = isRead;
    //    //    Rohab.ServiceReference1.GetInboxCountResponse retVal = ((Rohab.ServiceReference1.SendSoap)(this)).GetInboxCount(inValue);
    //    //    return retVal.Body.GetInboxCountResult;
    //    //}

    //    //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    //    //Rohab.ServiceReference1.getMessagesResponse Rohab.ServiceReference1.SendSoap.getMessages(Rohab.ServiceReference1.getMessagesRequest request) {
    //    //    return base.Channel.getMessages(request);
    //    //}

    //    //public Rohab.ServiceReference1.MessagesBL[] getMessages(string username, string password, int location, string from, int index, int count) {
    //    //    Rohab.ServiceReference1.getMessagesRequest inValue = new Rohab.ServiceReference1.getMessagesRequest();
    //    //    inValue.Body = new Rohab.ServiceReference1.getMessagesRequestBody();
    //    //    inValue.Body.username = username;
    //    //    inValue.Body.password = password;
    //    //    inValue.Body.location = location;
    //    //    inValue.Body.from = from;
    //    //    inValue.Body.index = index;
    //    //    inValue.Body.count = count;
    //    //    Rohab.ServiceReference1.getMessagesResponse retVal = ((Rohab.ServiceReference1.SendSoap)(this)).getMessages(inValue);
    //    //    return retVal.Body.getMessagesResult;
    //    //}
    //}
}
